# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run-script build
        touch .env
        echo API_ENDPOINT="https://xxx.execute-api.us-west-2.amazonaws.com" >> .env
        echo API_KEY=${{ secrets.API_KEY }} >> .env
        echo CONTACT_FORM: ${{ secrets.CONTACT_FORM }} >> .env
        echo CONTACT_SERVICE: ${{ secrets.CONTACT_SERVICE }} >> .env
        echo PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }} >> .env
        cat .env

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
